completed 3.6 GET/api
NadiaIb/Games pull request #3
Opened 2023-05-09 15:07 UTC by NadiaIb

2023-05-09 15:15 UTC, robert112233 requested changes
Create the endpoint with a test and submit another PR for review 👍

2023-05-09 15:15 UTC, robert112233 commented on endpoints.json
> +    }
The Json looks great, but you aren't sending it back to the client from what I can see. You should create an endpoint called /api which responds with the JSON that you have made. You can use readfile to extract the data. You shouldn't need a model because the query doesn't involve the db, just a controller.

2023-05-10 10:44 UTC, JVal-NC reviewed
Couple comments to consider

2023-05-10 10:44 UTC, JVal-NC commented on __tests__/app.test.js
> +          expect(categories).hasOwnProperty("slug");
Lines 35 and 36 unnecessary as we are asserting against these keys values on lines 37 and 38

2023-05-10 10:44 UTC, JVal-NC commented on __tests__/app.test.js
> +        expect(typeof response.body).toEqual("object");
Line 32 not needed

2023-05-10 10:44 UTC, JVal-NC commented on app.js
> +    fs.readFile("/endpoints.json", "utf8", function (err, data){
This looks. a bit funky. Please put it in a controller and use error handlers as I think this wouldn't feedback the errors to the client when using throw

2023-05-11 07:57 UTC, Augs0 approved these changes

2023-05-11 07:57 UTC, Augs0 commented on __tests__/app.test.js
> +  test("GET - status:200 - returns JSON with available endpoints ", () => {
This test is fine, but bear in mind that as the JSON file updates, this test will still pass, so it's important to come and check it still works every time, even though the test will remain the same :)

2023-05-11 07:57 UTC, Augs0 commented on __tests__/app.test.js
> +describe("/api/categories", () => {
Looks like some of task 3 has ended up on this PR. Be mindful not to mix up your tasks on the same branch

2023-05-11 07:57 UTC, Augs0 commented on __tests__/app.test.js
> +        const categories = response.body.category;
I like this - makes things a bit more readable

2023-05-11 11:01 UTC, merged